---
- name: Pull docker image of the SPE_BAckend
  hosts: all
  tasks:
#     - name: pull docker image
#       shell: docker pull dheer009/backend
      
#     - name: run docker image backend
#       shell: docker run -it -d dheer009/backend /bin/bash
    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: Pull Images
      command: docker-compose pull

    - name: Running Docker Compose File
      command: docker-compose -f docker-compose.yml up -d
